"""
Sites marked ALLOWED by checker_robots.py's most recent run.
BLOCKED and ERROR sites are excluded. Sites with a ⚠ WARNING comment
(policy language mentioning scraping/AI/LLM terms) are still included
here since they're technically ALLOWED — read their robots.txt by hand
before using them for anything beyond local testing.

Regenerate this file by hand after re-running checker_robots.py, or
wire it up to parse that script's output automatically later.
"""

ALLOWED_SITES = {
    "news": [
        "https://www.bbc.com",
        "https://www.nytimes.com",
        "https://www.theguardian.com",
        "https://apnews.com",
        "https://www.aljazeera.com",
        "https://www.washingtonpost.com",
        "https://www.usatoday.com",
        "https://www.nbcnews.com",
        "https://www.foxnews.com",
        "https://www.bloomberg.com",
        "https://www.euronews.com",
        "https://www.forbes.com",
        "https://www.ft.com",
        "https://www.cbc.ca",
        "https://www.dw.com",
        "https://www.lemonde.fr",
        "https://www.elpais.com",
        "https://www.ansa.it",
        "https://www.rte.ie",
        "https://www.smh.com.au",
        "https://www.straitstimes.com",
        "https://www.hindustantimes.com",
        "https://www.timesofisrael.com",
        "https://abcnews.go.com",
        "https://news.sky.com",
    ],
    "tech_company": [
        "https://www.google.com",
        "https://www.apple.com",
        "https://www.microsoft.com",
        "https://www.amazon.com",
        "https://www.meta.com",
        "https://www.spotify.com",
        "https://www.openai.com",
        "https://www.github.com",
        "https://www.gitlab.com",
        "https://www.ibm.com",
        "https://www.oracle.com",
        "https://www.nvidia.com",
        "https://www.salesforce.com",
        "https://www.paypal.com",
        "https://www.shopify.com",
        "https://www.airbnb.com",
        "https://www.uber.com",
        "https://www.dropbox.com",
        "https://www.cloudflare.com",
        "https://www.digitalocean.com",
    ],
    "docs_developer": [
        "https://docs.python.org",
        "https://docs.oracle.com",
        "https://kubernetes.io",
        "https://developer.mozilla.org",
        "https://docs.docker.com",
        "https://react.dev",
        "https://angular.io",
        "https://vuejs.org",
        "https://pytorch.org",
        "https://www.tensorflow.org",
        "https://numpy.org",
        "https://pandas.pydata.org",
        "https://go.dev",
        "https://docs.aws.amazon.com",
        "https://cloud.google.com",
        "https://learn.microsoft.com",
        "https://www.php.net",
    ],
    "educational_reference": [
        "https://www.wikipedia.org",
        "https://www.britannica.com",
        "https://www.khanacademy.org",
        "https://www.coursera.org",
        "https://www.edx.org",
        "https://ocw.mit.edu",
        "https://plato.stanford.edu",
        "https://www.nationalgeographic.com",
        "https://www.worldhistory.org",
        "https://www.sciencedaily.com",
        "https://www.howstuffworks.com",
        "https://www.investopedia.com",
        "https://www.mathsisfun.com",
        "https://www.famnit.upr.si",
    ],
    "government": [
        "https://www.whitehouse.gov",
        "https://www.europa.eu",
        "https://www.un.org",
        "https://www.who.int",
        "https://www.nasa.gov",
        "https://www.data.gov",
        "https://www.gov.uk",
        "https://www.bundesregierung.de",
        "https://www.australia.gov.au",
        "https://www.oecd.org",
    ],
}